import type { Icon } from './gfx';

/*
 * The pointer's shapes, drawn by the tube itself so they glow and trail like
 * everything else on the screen. '#' is the outline, 'o' the fill; each has its
 * hot spot, the pixel that points.
 */
export type CursorShape = 'arrow' | 'hand' | 'text' | 'wait' | 'move' | 'resize' | 'left' | 'right' | 'cross' | 'none';
export type Cursor = Icon & { hx: number; hy: number };

const INK = { '#': 'cursorLine', o: 'cursorFill' } as const;
const cursor = (rows: string[], hx: number, hy: number): Cursor => ({ w: Math.max(...rows.map(r => r.length)), h: rows.length, rows, ink: INK, hx, hy });

export const CURSORS: Record<Exclude<CursorShape, 'none'>, Cursor> = {
  arrow: cursor([
    '#',
    '##',
    '#o#',
    '#oo#',
    '#ooo#',
    '#oooo#',
    '#ooooo#',
    '#oooooo#',
    '#ooooooo#',
    '#oooooooo#',
    '#ooooo#####',
    '#oo#oo#',
    '#o# #oo#',
    '##  #oo#',
    '#    #oo#',
    '     #oo#',
    '      #oo#',
    '      #oo#',
    '       ##',
  ], 0, 0),
  hand: cursor([
    '    ##',
    '   #oo#',
    '   #oo#',
    '   #oo#',
    '   #oo###',
    '   #oo#oo###',
    '## #oo#oo#oo##',
    '#oo#oo#oo#oo#o#',
    '#ooooooooooo#o#',
    ' #oooooooooooo#',
    '  #ooooooooooo#',
    '  #oooooooooo#',
    '   #ooooooooo#',
    '   #oooooooo#',
    '    #ooooooo#',
    '    #########',
  ], 5, 0),
  text: cursor([
    '###.###'.replace(/\./g, ' '),
    '   #',
    '   #',
    '   #',
    '   #',
    '   #',
    '   #',
    '   #',
    '   #',
    '   #',
    '   #',
    '   #',
    '   #',
    '   #',
    '### ###',
  ].map(r => r.replace(/#/g, 'o')), 3, 7),
  wait: cursor([
    '###########',
    '#ooooooooo#',
    ' #ooooooo#',
    ' #o#o#o#o#',
    '  #o#o#o#',
    '   #o#o#',
    '    #o#',
    '    #o#',
    '   #ooo#',
    '  #oo#oo#',
    ' #oo#o#oo#',
    ' #o#o#o#o#',
    '#ooooooooo#',
    '###########',
  ], 5, 7),
  move: cursor([
    '      #',
    '     #o#',
    '    #ooo#',
    '   ###o###',
    '  #  #o#  #',
    ' ##  #o#  ##',
    '#o#########o#',
    'ooooooooooooo',
    '#o#########o#',
    ' ##  #o#  ##',
    '  #  #o#  #',
    '   ###o###',
    '    #ooo#',
    '     #o#',
    '      #',
  ], 6, 7),
  resize: cursor([
    '######',
    '#oooo#',
    '#ooo#',
    '#oooo#',
    '#o##oo#',
    '##  #oo#',
    '     #oo#  ##',
    '      #oo##o#',
    '       #oooo#',
    '        #ooo#',
    '       #oooo#',
    '       ######',
  ], 6, 6),
  left: cursor([
    '     ##',
    '    #o#',
    '   #oo#',
    '  #ooo######',
    ' #ooooooooo#',
    '#oooooooooo#',
    ' #ooooooooo#',
    '  #ooo######',
    '   #oo#',
    '    #o#',
    '     ##',
  ], 0, 5),
  right: cursor([
    '     ##',
    '     #o#',
    '     #oo#',
    '######ooo#',
    '#ooooooooo#',
    '#oooooooooo#',
    '#ooooooooo#',
    '######ooo#',
    '     #oo#',
    '     #o#',
    '     ##',
  ], 11, 5),
  cross: cursor([
    '     #',
    '     o',
    '     o',
    '     o',
    '',
    '#ooo   ooo#',
    '',
    '     o',
    '     o',
    '     o',
    '     #',
  ], 5, 5),
};
