"""
Builds components/terminal/graphics/webtype-data.ts: the type NAVIGATOR sets pages in.

  BODY   Fusion Pixel 12px proportional (SIL OFL 1.1): every character the pages use,
         as bitmaps, one row of up to 12 bits a line, 14 lines a glyph.
  SMALL  Fusion Pixel 8px monospaced: printable ASCII, for dates and small print.
  SERIF  Gentilis (a Gentium, SIL OFL 1.1): printable ASCII as outlines, for headlines.

The characters come from the pages themselves, so run this again after changing them:

    python scripts/build-terminal-webtype.py
"""
import json, re
from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / 'public' / 'fonts'
OUT = ROOT / 'components' / 'terminal' / 'graphics' / 'webtype-data.ts'
TERMINAL = ROOT / 'components' / 'terminal'
SOURCES = [TERMINAL / 'content' / 'web', TERMINAL / 'content' / 'board.ts', TERMINAL / 'content' / 'messages.ts', TERMINAL / 'content' / 'browser.ts']
EXTRA = '·…—–“”‘’（）【】《》「」『』、。，：；！？～♥◄►▲▼←→↗★☆○●◎□■§№'
ROWS = (2, 16)  # the rows of the 16-line cell a glyph can use


def characters():
    chars = set(chr(c) for c in range(32, 127)) | set(EXTRA)
    for src in SOURCES:
        files = src.rglob('*.ts') if src.is_dir() else [src]
        for f in files:
            if f.exists():
                chars |= {c for c in f.read_text(encoding='utf8') if ord(c) >= 32 and c not in '  '}
    return sorted(chars)


def bitmap(font, ch, cols, span):
    im = Image.new('L', (32, 20), 0)
    ImageDraw.Draw(im).text((0, 0), ch, font=font, fill=255)
    a = np.asarray(im) > 127
    rows = []
    for y in range(*span):
        bits = 0
        for x in range(cols):
            if a[y, x]: bits |= 1 << (cols - 1 - x)
        rows.append(bits)
    return rows


QUANT = 4  # outline units are stored divided by this: a fifth of a pixel at the largest headline


def flatten(outline, steps=3):
    toks, out, cur, i = outline.split(), [], None, 0
    while i < len(toks):
        c = toks[i]
        if c == 'm': cur = [(float(toks[i + 1]), float(toks[i + 2]))]; out.append(cur); i += 3
        elif c == 'l': cur.append((float(toks[i + 1]), float(toks[i + 2]))); i += 3
        elif c == 'q':
            x, y, cx, cy = map(float, toks[i + 1:i + 5]); x0, y0 = cur[-1]
            for k in range(1, steps + 1):
                t = k / steps; cur.append(((1 - t) ** 2 * x0 + 2 * (1 - t) * t * cx + t * t * x, (1 - t) ** 2 * y0 + 2 * (1 - t) * t * cy + t * t * y))
            i += 5
        elif c == 'b':
            x, y, c1x, c1y, c2x, c2y = map(float, toks[i + 1:i + 7]); x0, y0 = cur[-1]
            for k in range(1, steps + 1):
                t = k / steps; u = 1 - t
                cur.append((u ** 3 * x0 + 3 * u * u * t * c1x + 3 * u * t * t * c2x + t ** 3 * x, u ** 3 * y0 + 3 * u * u * t * c1y + 3 * u * t * t * c2y + t ** 3 * y))
            i += 7
        else: i += 1
    cleaned = []
    for c in out:
        pts = []
        for x, y in c:
            q = (round(x / QUANT), round(y / QUANT))
            if not pts or pts[-1] != q: pts.append(q)
        if len(pts) > 2: cleaned.append([v for p in pts for v in p])
    return cleaned


def main():
    body = ImageFont.truetype(str(FONTS / 'fusion-pixel' / 'fusion-pixel-12px-proportional-latin.otf.woff2'), 12)
    small = ImageFont.truetype(str(FONTS / 'fusion-pixel' / 'fusion-pixel-8px-monospaced-latin.otf.woff2'), 8)
    chars = characters()
    lines = [
        '// Generated by scripts/build-terminal-webtype.py from Fusion Pixel and Gentilis',
        '// (public/fonts; both SIL Open Font License 1.1). Do not edit by hand.',
        '',
        '/** A bitmap face: each glyph its advance and its rows (hex, `cols` bits a row, top row first). */',
        'export type BitmapFace = { rows: number; cols: number; glyphs: Readonly<Record<string, readonly [number, string]>> };',
        '/** An outline face: each glyph its advance and its outlines (x, y pairs, y up), in `units` to the em. */',
        'export type OutlineFace = { units: number; ascent: number; capHeight: number; glyphs: Readonly<Record<string, readonly [number, readonly (readonly number[])[]]>> };',
        '',
    ]
    def face(name, font, chars, cols, span):
        lines.append(f'export const {name}: BitmapFace = {{ rows: {span[1] - span[0]}, cols: {cols}, glyphs: {{')
        width = (cols + 3) // 4
        for ch in chars:
            adv = int(round(font.getlength(ch)))
            rows = ''.join(f'{r:0{width}x}' for r in bitmap(font, ch, cols, span))
            lines.append(f'  {json.dumps(ch, ensure_ascii=False)}: [{adv}, \'{rows}\'],')
        lines.append('} };')
        lines.append('')
    face('BODY', body, chars, 12, ROWS)
    face('SMALL', small, [chr(c) for c in range(32, 127)], 8, (0, 10))
    serif = json.loads((FONTS / 'gentilis_regular.typeface.json').read_text(encoding='utf8'))
    cap = max(p for c in flatten(serif['glyphs']['H']['o']) for p in c[1::2])
    lines.append(f"export const SERIF: OutlineFace = {{ units: {serif['resolution'] / QUANT}, ascent: {round(serif['ascender'] / QUANT)}, capHeight: {cap}, glyphs: {{")
    for c in range(32, 127):
        ch = chr(c); g = serif['glyphs'].get(ch)
        if not g: continue
        lines.append(f'  {json.dumps(ch)}: [{round(float(g["ha"]) / QUANT)}, {json.dumps(flatten(g.get("o", "")), separators=(",", ":"))}],')
    lines.append('} };')
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf8')
    print(f'wrote {OUT.relative_to(ROOT)}: {len(chars)} body glyphs, {OUT.stat().st_size // 1024} KB')


if __name__ == '__main__':
    main()
