"""
Builds components/terminal/content/mark-glyphs.ts: the outlines of J, R and & for
the terminal's nameplate, taken from Outfit SemiBold (public/fonts, SIL Open Font
License 1.1), with the curves flattened to straight segments.

    python scripts/build-terminal-mark.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / 'public' / 'fonts' / 'Outfit SemiBold_Regular.json'
OUT = ROOT / 'components' / 'terminal' / 'content' / 'mark-glyphs.ts'
STEPS = 6


def contours(outline):
    toks, out, cur, i = outline.split(), [], None, 0
    while i < len(toks):
        c = toks[i]
        if c == 'm':
            cur = [(float(toks[i + 1]), float(toks[i + 2]))]
            out.append(cur)
            i += 3
        elif c == 'l':
            cur.append((float(toks[i + 1]), float(toks[i + 2])))
            i += 3
        elif c == 'q':
            # typeface.js: the end point first, then the control point.
            x, y, cx, cy = map(float, toks[i + 1:i + 5])
            x0, y0 = cur[-1]
            for k in range(1, STEPS + 1):
                t = k / STEPS
                cur.append(((1 - t) ** 2 * x0 + 2 * (1 - t) * t * cx + t * t * x, (1 - t) ** 2 * y0 + 2 * (1 - t) * t * cy + t * t * y))
            i += 5
        elif c == 'b':
            x, y, c1x, c1y, c2x, c2y = map(float, toks[i + 1:i + 7])
            x0, y0 = cur[-1]
            for k in range(1, STEPS + 1):
                t = k / STEPS
                u = 1 - t
                cur.append((u ** 3 * x0 + 3 * u * u * t * c1x + 3 * u * t * t * c2x + t ** 3 * x, u ** 3 * y0 + 3 * u * u * t * c1y + 3 * u * t * t * c2y + t ** 3 * y))
            i += 7
        else:
            i += 1
    # Closed shapes need no repeated last point.
    return [[p for j, p in enumerate(c) if j == 0 or p != c[j - 1]] for c in out]


def main():
    font = json.loads(FONT.read_text(encoding='utf8'))
    lines = [
        '// Generated by scripts/build-terminal-mark.py from Outfit SemiBold',
        '// (public/fonts; SIL Open Font License 1.1). Do not edit by hand.',
        '',
        '/** A glyph: its advance and its outlines, in font units (y up, baseline 0, capitals 976 tall). */',
        'export type OutlineGlyph = { advance: number; contours: readonly (readonly number[])[] };',
        '',
        'export const CAP_HEIGHT = 976;',
        '',
        'export const GLYPHS: Readonly<Record<\'J\' | \'R\' | \'&\', OutlineGlyph>> = {',
    ]
    for ch in 'JR&':
        g = font['glyphs'][ch]
        cs = contours(g['o'])
        lines.append(f"  '{ch}': {{")
        lines.append(f"    advance: {int(g['ha'])},")
        lines.append('    contours: [')
        for c in cs:
            flat = ', '.join(f'{round(x)}, {round(y)}' for x, y in c)
            lines.append(f'      [{flat}],')
        lines.append('    ],')
        lines.append('  },')
    lines.append('};')
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf8')
    print(f'wrote {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
